<a href="https://colab.research.google.com/github/YarkoMarko/Numpy_DZ/blob/main/module2/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [ ]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [98]:
a = np.array([i for i in range(30, 71, 2)])
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [100]:
b = np.array([i for i in np.arange(0, 1, 0.1)])
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [103]:
def func(c):
  d = np.zeros((len(c) + 2, len(c) + 2))
  for i in range(len(d)):
    if i != 0 and i != len(d) - 1:
      seq = []
      for j in range(len(c) + 2):
        if j != 0 and j != len(c) + 1:
          seq.append(c[i - 1][j - 1])

        else:
          seq.append(0)

      d[i] = np.array(seq)

  return d


c = np.array([[1, 2], [3, 4]])

print(func(c))

[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [104]:
print(c.dtype)
c.dtype = np.float64
print(c.dtype)

int64
float64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [105]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
mask = x < var
mask2 = x > var
mask3 = x == var
x[mask] = -1
x[mask2] = -1
x[mask3] = -1
x

array([-1, -1, -1, -1, -1, -1, -1, -1])

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [106]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

mask_ = np.isnan(X)
X[mask_] = -1
X

array([[ 1.,  2., -1.,  4.],
       [ 5., -1., -1.,  4.],
       [-1., 10., 11., -1.]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [107]:
q = np.ones((3, 4))
print(sum(q[:]) / len(q[:]))

[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [109]:
z = np.random.random((5, 6))
z = np.round(z, 1)
z[0] = sorted(z[0])
z

array([[0. , 0.1, 0.2, 0.6, 0.8, 0.9],
       [0.5, 0.3, 0.3, 0.9, 0.2, 0.9],
       [0.9, 0.4, 0.9, 0.8, 0.7, 0.1],
       [0.6, 0.1, 0.7, 0.9, 0.8, 1. ],
       [0.6, 0.4, 0.1, 0.8, 0.7, 0.5]])

#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [114]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

mask_1 = np.logical_and(X > 3, X < 6)
X[mask_1]

array([4, 5, 5, 4])

#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]

In [146]:
v = np.random.randint(0, 100, size=(5, 6))
v = (v - np.min(v)) / (np.max(v) - np.min(v))
v

array([[0.62244898, 0.58163265, 0.15306122, 0.13265306, 0.        ,
        0.43877551],
       [0.51020408, 0.85714286, 1.        , 0.09183673, 0.3877551 ,
        0.56122449],
       [0.21428571, 0.39795918, 0.91836735, 0.18367347, 0.17346939,
        0.17346939],
       [0.34693878, 0.06122449, 0.10204082, 0.73469388, 0.26530612,
        0.        ],
       [0.89795918, 0.15306122, 0.42857143, 0.25510204, 0.30612245,
        0.13265306]])